version: '2'
services:
    pdfgen-app:
        image: pdfgen
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pdfgen-postgresql:5432/pdfgen
            - JHIPSTER_CACHE_MEMCACHED_SERVERS=pdfgen-memcached:11211
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
        ports:
            - 8080:8080
    pdfgen-postgresql:
        extends:
            file: postgresql.yml
            service: pdfgen-postgresql
    pdfgen-memcached:
        extends:
            file: memcached.yml
            service: pdfgen-memcached
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
